// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[xxx]/test.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/personal.ts";
import * as $4 from "./routes/company/[id].tsx";
import * as $5 from "./routes/company/index.tsx";
import * as $6 from "./routes/company/test/[id].tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/personal/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/forms/Personal.tsx";

const manifest = {
  routes: {
    "./routes/[xxx]/test.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/personal.ts": $3,
    "./routes/company/[id].tsx": $4,
    "./routes/company/index.tsx": $5,
    "./routes/company/test/[id].tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/personal/index.tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/forms/Personal.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
