FROM denoland/deno:alpine-1.34.3
RUN apk add curl build-base
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64

RUN mkdir -p /tools
RUN mv /tailwindcss-linux-x64 /tools/tailwindcss

EXPOSE 8000
WORKDIR /app